import "server-only";
import { getViewer } from "@/lib/auth/viewer";
import { createClient } from "@/lib/supabase/server";

export type AnalyticsScope = "company" | "store" | "rep";
type Interaction = { user_id: string; location_id: string | null; question: string; topic: string; product_references: string[]; competitor_references: string[]; objection_category: string | null; grounded: boolean; unresolved: boolean; created_at: string };
type Member = { user_id: string; role: string; location_id: string | null; profiles: { full_name: string | null } | null; locations: { name: string } | null };
const dateRange = (value?: string) => { const now = new Date(); const days = value === "7" ? 7 : value === "90" ? 90 : 30; return new Date(now.getTime() - days * 86400000).toISOString(); };
const tally = (items: string[]) => Object.entries(items.reduce<Record<string, number>>((out, item) => { if (item) out[item] = (out[item] || 0) + 1; return out; }, {})).sort((a, b) => b[1] - a[1]).slice(0, 8).map(([label, count]) => ({ label, count }));

export async function getAssistantAnalytics(input: { view?: string; location?: string; rep?: string; days?: string }) {
  const viewer = await getViewer(); if (!viewer?.organizationId || viewer.demo) return { allowed: false, reason: "Sign in to view Sales Assistant analytics." } as const;
  const supabase = await createClient(); const isAdmin = viewer.role === "tenant_admin" || viewer.role === "platform_owner";
  const [{ data: memberships }, { data: assignments }] = await Promise.all([supabase.from("organization_memberships").select("user_id,role,location_id,profiles(full_name),locations(name)").eq("organization_id", viewer.organizationId).eq("status", "active"), supabase.from("organization_member_locations").select("location_id").eq("organization_id", viewer.organizationId).eq("user_id", viewer.id)]);
  const managerLocations = (assignments || []).map((item) => item.location_id); const permittedMembers = ((memberships || []) as unknown as Member[]).filter((member) => isAdmin || member.user_id === viewer.id || (viewer.role === "manager" && member.location_id && managerLocations.includes(member.location_id)));
  const permittedLocations = [...new Map(permittedMembers.filter((m) => m.location_id).map((m) => [m.location_id!, m.locations?.name || "Unassigned"])).entries()].map(([id, name]) => ({ id, name }));
  const requestedView: AnalyticsScope = input.view === "company" || input.view === "store" || input.view === "rep" ? input.view : (viewer.role === "salesperson" ? "rep" : "company");
  const scope: AnalyticsScope = viewer.role === "salesperson" ? "rep" : requestedView; const locationId = permittedLocations.some((l) => l.id === input.location) ? input.location : (viewer.role === "manager" ? permittedLocations[0]?.id : undefined); const repId = permittedMembers.some((m) => m.user_id === input.rep) ? input.rep : viewer.id;
  let query = supabase.from("assistant_interactions").select("user_id,location_id,question,topic,product_references,competitor_references,objection_category,grounded,unresolved,created_at").eq("organization_id", viewer.organizationId).gte("created_at", dateRange(input.days)).order("created_at", { ascending: false });
  if (scope === "store" && locationId) query = query.eq("location_id", locationId); if (scope === "rep") query = query.eq("user_id", repId); if (scope === "company" && !isAdmin && viewer.role === "manager") query = query.in("location_id", permittedLocations.map((l) => l.id));
  const { data } = await query; const interactions = (data || []) as Interaction[]; const ids = new Set(interactions.map((item) => item.user_id)); const totals = { conversations: interactions.length, questions: interactions.length, activeUsers: ids.size, activeReps: permittedMembers.filter((m) => m.role === "salesperson" && ids.has(m.user_id)).length, averagePerRep: ids.size ? Math.round(interactions.length / ids.size * 10) / 10 : 0, grounded: interactions.filter((item) => item.grounded).length, unresolved: interactions.filter((item) => item.unresolved).length };
  const daily = tally(interactions.map((item) => item.created_at.slice(0, 10))).reverse(); const membersById = new Map(permittedMembers.map((m) => [m.user_id, m])); const reps = [...ids].map((id) => ({ id, name: membersById.get(id)?.profiles?.full_name || "Team member", questions: interactions.filter((i) => i.user_id === id).length })).sort((a, b) => b.questions - a.questions);
  const stores = permittedLocations.map((store) => ({ ...store, questions: interactions.filter((item) => item.location_id === store.id).length, users: new Set(interactions.filter((item) => item.location_id === store.id).map((item) => item.user_id)).size }));
  return { allowed: true, scope, days: input.days || "30", locations: permittedLocations, reps, stores, selectedLocation: locationId || "", selectedRep: repId, totals, trend: daily, topics: tally(interactions.map((i) => i.topic)), products: tally(interactions.flatMap((i) => i.product_references || [])), competitors: tally(interactions.flatMap((i) => i.competitor_references || [])), objections: tally(interactions.map((i) => i.objection_category || "")), unresolved: interactions.filter((i) => i.unresolved).slice(0, 8), recent: interactions.slice(0, 8) } as const;
}
