import Link from "next/link";
import { ArrowRight, Award, BookOpenCheck, Clock3, Play, Target, TrendingUp } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { getCoachDashboardData } from "@/lib/coach/data";
import { demoCloserScores } from "@/lib/coach/demo";

export default async function CoachDashboardPage() {
  const data = await getCoachDashboardData();
  const recommended = data.scenarios[0];
  const scores = data.recentSessions[0]?.closerScores.length ? data.recentSessions[0].closerScores : demoCloserScores;
  return <AppShell title="Sales Coach"><PageHeader eyebrow="Practice with purpose" title="Build confidence one conversation at a time" description="Use structured BGC practice scenarios and C.L.O.S.E.R.-based coaching to sharpen the skills that matter most." action={<Link className="btn btn-primary" href="/coach/scenarios"><Play size={16}/> Start practice</Link>}/><p className="callout"><strong>Reporting scope:</strong> {data.scopeLabel}</p>
    {data.error && <div className="card error-card"><h2>Coach data unavailable</h2><p>{data.error}</p></div>}
    <div className="grid grid-4"><div className="card"><div className="metric-row"><span>Practice sessions</span><span className="metric-icon"><BookOpenCheck size={18}/></span></div><div className="metric">{data.practiceSessions}</div><span className="delta">{data.source === "demo" ? "Sample activity" : "Saved sessions"}</span></div><div className="card"><div className="metric-row"><span>Available scenarios</span><span className="metric-icon"><Award size={18}/></span></div><div className="metric">{data.scenarios.length}</div><span className="delta">Published practice</span></div><div className="card"><div className="metric-row"><span>Average score</span><span className="metric-icon"><TrendingUp size={18}/></span></div><div className="metric">{data.averageScore === null ? "—" : `${data.averageScore}%`}</div><span className="delta">{data.averageScore === null ? "Complete a session" : "Saved performance"}</span></div><div className="card"><div className="metric-row"><span>Recent activity</span><span className="metric-icon"><Clock3 size={18}/></span></div><div className="metric">{data.recentSessions.length}</div><span className="delta">Reviewable sessions</span></div></div>
    <div className="coach-dashboard-grid">{recommended ? <section className="card"><div className="metric-row"><div><span className="badge amber">Recommended next</span><h2 className="coach-heading">{recommended.title}</h2></div><Target size={30}/></div><p>{recommended.goal}</p><div className="chips">{recommended.skills.map((skill) => <span className="chip" key={skill}>{skill}</span>)}</div><Link className="btn btn-primary" href={`/coach/session?scenario=${recommended.slug}`}>Begin {recommended.duration} practice <ArrowRight size={16}/></Link></section> : <section className="card output empty"><div><h2>No scenarios available</h2><p>A workspace administrator can publish the first scenario.</p></div></section>}
      <section className="card"><div className="metric-row"><h2>C.L.O.S.E.R. skill profile</h2><Link className="text-button" href="/coach/review">View review <ArrowRight size={14}/></Link></div><div className="coach-scores">{scores.map(([skill, score]) => <div key={skill}><span>{skill}</span><div className="progress"><span style={{ width: `${score}%` }}/></div><strong>{score}</strong></div>)}</div></section></div>
    <div className="section-heading"><h2>More ways to practice</h2><Link className="text-button" href="/coach/scenarios">View all scenarios <ArrowRight size={14}/></Link></div><div className="grid grid-3">{data.scenarios.slice(1, 4).map((scenario) => <Link className="card quick-card" href={`/coach/session?scenario=${scenario.slug}`} key={scenario.id}><span className="metric-icon"><Play size={17}/></span><div><span className="badge blue">{scenario.difficulty}</span><h3>{scenario.title}</h3><p>{scenario.category} · {scenario.duration}</p></div></Link>)}</div>
    {data.recentSessions.length > 0 && <><div className="section-heading"><h2>Recent practice history</h2></div><div className="card activity">{data.recentSessions.map((session) => <Link className="activity-row" href={`/coach/review?session=${session.id}`} key={session.id}><span className="metric-icon"><TrendingUp size={17}/></span><p><strong>{session.scenarioTitle}</strong><small style={{ display: "block" }}>{session.participantName ? `${session.participantName} · ` : ""}{session.locationName ? `${session.locationName} · ` : ""}{new Date(session.completedAt).toLocaleDateString()} · {session.score}%</small></p><ArrowRight size={17}/></Link>)}</div></>}
  </AppShell>;
}
