import Link from "next/link";
import { AlertTriangle, ArrowRight, BarChart3, CheckCircle2, Info, MapPin, TrendingDown, TrendingUp } from "lucide-react";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { getExecutiveTrends } from "@/lib/executive/trends-repository";

const monthLabel = (period: string) => new Date(`${period}-01T12:00:00`).toLocaleDateString(undefined, { month: "short", year: "numeric" });
const money = (value: number) => new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const signed = (value: number, suffix = "") => `${value > 0 ? "+" : ""}${value.toLocaleString()}${suffix}`;

export default async function ExecutiveTrendsPage({ searchParams }: { searchParams: Promise<{ months?: string; location?: string; from?: string; to?: string }> }) {
  const query = await searchParams;
  const data = await getExecutiveTrends(query);
  if (!data.canView) redirect("/dashboard");
  const latest = data.periods.at(-1);
  const maximumRevenue = Math.max(1, ...data.periods.flatMap((item) => [item.revenueTarget, item.revenueActual]));
  const locationQuery = data.selectedLocation === "all" ? "" : `&location=${encodeURIComponent(data.selectedLocation)}`;
  return <AppShell title="Executive Trends">
    <PageHeader eyebrow="Executive Advisor" title="See verified performance across reporting periods" description="Compare approved monthly sales activity and leadership-review completion without forecasts or inferred values." action={<Link className="btn btn-secondary" href="/executive"><ArrowRight size={16}/> Command center</Link>}/>
    <div className="callout executive-disclaimer"><Info size={20}/><div><strong>{data.persistence === "supabase" ? "Approved tenant history" : "Explainable demo history"}</strong><p>Every point represents an approved monthly sales record. Missing months remain missing and are never estimated.</p></div></div>
    {data.error && <p className="form-error executive-data-error"><AlertTriangle size={15}/>Some historical records could not be loaded: {data.error}</p>}
    <div className="trend-toolbar"><nav className="trend-range" aria-label="Trend range"><span>Show:</span><Link className={data.months === 6 ? "active" : ""} href={`/executive/trends?months=6${locationQuery}`}>6 months</Link><Link className={data.months === 12 ? "active" : ""} href={`/executive/trends?months=12${locationQuery}`}>12 months</Link></nav><form action="/executive/trends" method="get"><input type="hidden" name="months" value={data.months}/><label><MapPin size={15}/><span className="sr-only">Location</span><select className="input" name="location" defaultValue={data.selectedLocation}><option value="all">All approved locations</option>{data.locations.map((location) => <option value={location.id} key={location.id}>{location.name}</option>)}</select></label><button className="btn btn-secondary" type="submit">Apply location</button></form></div>

    {data.periods.length ? <>
      <section className="grid grid-4 executive-metrics" aria-label="Latest approved period"><article className="card"><span>Latest approved period</span><div className="metric metric-small">{monthLabel(latest!.period)}</div><small>{latest!.approvedLocations} approved location{latest!.approvedLocations === 1 ? "" : "s"}</small></article><article className="card"><span>Sales pace</span><div className="metric">{latest!.salesPace === null ? "—" : `${latest!.salesPace}%`}</div><small>Actual revenue ÷ approved target</small></article><article className="card"><span>Month-over-month</span><div className={`metric trend-change ${data.change === null ? "neutral" : data.change >= 0 ? "positive" : "attention"}`}>{data.change === null ? "—" : <>{data.change >= 0 ? <TrendingUp size={24}/> : <TrendingDown size={24}/>} {signed(data.change, " pts")}</>}</div><small>Change in approved sales pace</small></article><article className="card"><span>Leadership review</span><div className="metric metric-small">{latest!.reviewCompleted ? "Complete" : "Pending"}</div><small>Organization-wide monthly record</small></article></section>

      {data.comparison && <section className="card executive-period-comparison"><div className="metric-row"><div><span className="badge blue">Selected comparison</span><h2>Compare two approved periods</h2><p>Choose any two available months for the current location filter.</p></div><TrendingUp size={21}/></div><form action="/executive/trends" method="get"><input type="hidden" name="months" value={data.months}/><input type="hidden" name="location" value={data.selectedLocation}/><label><span className="label">Starting period</span><select className="input" name="from" defaultValue={data.comparison.from.period}>{data.periods.map((item) => <option value={item.period} key={item.period}>{monthLabel(item.period)}</option>)}</select></label><label><span className="label">Comparison period</span><select className="input" name="to" defaultValue={data.comparison.to.period}>{data.periods.map((item) => <option value={item.period} key={item.period}>{monthLabel(item.period)}</option>)}</select></label><button className="btn btn-secondary" type="submit">Compare periods</button></form><div className="comparison-periods"><article><small>Starting period</small><strong>{monthLabel(data.comparison.from.period)}</strong><span>{money(data.comparison.from.revenueActual)} actual · {data.comparison.from.salesPace ?? "—"}% pace</span></article><div className="comparison-deltas"><span><small>Revenue</small><strong>{signed(data.comparison.revenueChange)}</strong></span><span><small>Sales pace</small><strong>{data.comparison.paceChange === null ? "—" : signed(data.comparison.paceChange, " pts")}</strong></span><span><small>Units</small><strong>{signed(data.comparison.unitChange)}</strong></span><span><small>Leads</small><strong>{signed(data.comparison.leadChange)}</strong></span><span><small>Appointments</small><strong>{signed(data.comparison.appointmentChange)}</strong></span></div><article><small>Comparison period</small><strong>{monthLabel(data.comparison.to.period)}</strong><span>{money(data.comparison.to.revenueActual)} actual · {data.comparison.to.salesPace ?? "—"}% pace</span></article></div></section>}

      <section className="card executive-trend-chart"><div className="metric-row"><div><span className="badge blue">Approved revenue</span><h2>Actual compared with target</h2><p>{data.selectedLocation === "all" ? "Combined across locations with approved records in each month." : `Filtered to ${data.locations.find((item) => item.id === data.selectedLocation)?.name}.`}</p></div><BarChart3 size={22}/></div><div className="trend-legend"><span><i className="actual"/>Actual</span><span><i/>Target</span></div><div className="trend-bars">{data.periods.map((item) => <div key={item.period}><strong>{monthLabel(item.period)}</strong><div><span className="trend-bar target" style={{ width: `${Math.round(item.revenueTarget / maximumRevenue * 100)}%` }}><small>{money(item.revenueTarget)}</small></span><span className="trend-bar actual" style={{ width: `${Math.round(item.revenueActual / maximumRevenue * 100)}%` }}><small>{money(item.revenueActual)}</small></span></div></div>)}</div></section>

      <section className="card executive-trend-table"><div className="section-heading"><div><span className="badge blue">Source detail</span><h2>Approved monthly activity</h2><p>Counts and totals are direct sums of approved location records.</p></div></div><div className="executive-table-scroll"><table><thead><tr><th>Period</th><th>Locations</th><th>Sales pace</th><th>Units</th><th>Leads</th><th>Appointments</th><th>Review</th></tr></thead><tbody>{data.periods.toReversed().map((item) => <tr key={item.period}><td><strong>{monthLabel(item.period)}</strong></td><td>{item.approvedLocations}</td><td>{item.salesPace === null ? "—" : `${item.salesPace}%`}</td><td>{item.unitsActual} / {item.unitsTarget}</td><td>{item.leads}</td><td>{item.appointments}</td><td><span className={`badge ${item.reviewCompleted ? "blue" : "amber"}`}>{item.reviewCompleted ? "Complete" : "Pending"}</span></td></tr>)}</tbody></table></div></section>
    </> : <div className="card output empty executive-trend-empty"><CheckCircle2 size={30}/><h2>No approved historical results</h2><p>Approve monthly location results to begin the Executive trend history. Draft and missing records are intentionally excluded.</p><Link className="btn btn-secondary" href="/admin/sales-results">Open sales results</Link></div>}
  </AppShell>;
}
