"use client";

import { LoaderCircle, Send, Sparkles, Trophy } from "lucide-react";
import { useState } from "react";

type Message = { speaker: "customer" | "rep"; content: string };
export function AdaptiveCoachSession({ initialMode = "role_play" }: { initialMode?: "role_play" | "objection" | "challenge" }) {
  const [mode, setMode] = useState(initialMode); const [sessionId, setSessionId] = useState(""); const [messages, setMessages] = useState<Message[]>([]); const [reply, setReply] = useState(""); const [focus, setFocus] = useState(""); const [difficulty, setDifficulty] = useState(""); const [result, setResult] = useState<any>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function call(body: any) { const response = await fetch("/api/coach/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "The coach is unavailable."); return data; }
  async function start() { setLoading(true); setError(""); setResult(null); try { const data = await call({ action: "start", mode }); setSessionId(data.sessionId); setMessages([{ speaker: "customer", content: data.opening }]); setFocus(data.focus); setDifficulty(data.difficulty); } catch (e) { setError(e instanceof Error ? e.message : "Unable to start practice."); } finally { setLoading(false); } }
  async function send() { if (!reply.trim() || !sessionId) return; const text = reply.trim(); setReply(""); setMessages((current) => [...current, { speaker: "rep", content: text }]); setLoading(true); setError(""); try { const data = await call({ action: "reply", sessionId, reply: text }); setMessages((current) => [...current, { speaker: "customer", content: data.reply }]); } catch (e) { setError(e instanceof Error ? e.message : "Unable to continue practice."); } finally { setLoading(false); } }
  async function complete() { setLoading(true); setError(""); try { setResult(await call({ action: "complete", sessionId })); } catch (e) { setError(e instanceof Error ? e.message : "Unable to evaluate practice."); } finally { setLoading(false); } }
  if (result) return <section className="card"><span className="badge blue"><Trophy size={14}/> Adaptive review</span><h2>{result.score}% · {result.difficulty}</h2><p>{result.summary}</p><div className="grid grid-2"><div><strong>What worked</strong><p>{result.strength}</p></div><div><strong>Next focus</strong><p>{result.improvement}</p></div></div><div className="coach-scores">{Object.entries(result.skills).map(([skill, score]) => <div key={skill}><span>{skill}</span><div className="progress"><span style={{ width: `${score}%` }}/></div><strong>{String(score)}</strong></div>)}</div><button className="btn btn-primary" onClick={start}>Try the recommended next challenge</button></section>;
  return <section className="coach-session-grid"><div className="card coach-conversation"><div className="coach-card-head"><div><span className="badge blue">Adaptive AI practice</span><h2>{sessionId ? `${difficulty} conversation` : "Choose a practice mode"}</h2></div><Sparkles size={24}/></div>{!sessionId ? <><p>Every customer persona and difficulty level is generated from your saved development profile. Customer details stay hidden.</p><label className="label">Practice mode</label><select className="input" value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="role_play">Dynamic role-play</option><option value="objection">Practice an objection</option><option value="challenge">Challenge Me</option></select><button className="btn btn-primary" onClick={start} disabled={loading}>{loading ? <LoaderCircle className="spin" size={16}/> : <Sparkles size={16}/>} Start adaptive practice</button></> : <><div className="coach-chat" aria-live="polite">{messages.map((message, index) => <div className={`message ${message.speaker === "rep" ? "user" : "ai"}`} key={`${message.speaker}-${index}`}><strong>{message.speaker === "rep" ? "You" : "Customer"}</strong><p>{message.content}</p></div>)}</div><textarea className="input" rows={4} value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Respond naturally to the customer…" disabled={loading}/><div className="coach-actions"><button className="btn btn-primary" onClick={send} disabled={loading || !reply.trim()}><Send size={16}/> Send response</button><button className="btn btn-ghost" onClick={complete} disabled={loading || messages.filter((m) => m.speaker === "rep").length < 2}>End and evaluate</button></div></>}{error && <p className="form-error">{error}</p>}</div><aside className="coach-side-stack"><section className="card"><span className="badge amber">Your adaptive focus</span><h2>{focus || "Your profile will set the focus"}</h2><p>Use approved product knowledge, listen for the customer’s priorities, and avoid unverified promises.</p></section><section className="card"><h2>How it adapts</h2><p>Scores update your persistent profile after each session. Future customer pressure, objections, and coaching focus respond to demonstrated strengths and gaps.</p></section></aside></section>;
}
