"use client";
import { Calculator, LoaderCircle, Save } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { saveGrowthScoring } from "@/app/admin/growth/actions";
import { calculateGrowthPriority, type GrowthOpportunity, type GrowthScore, type GrowthScoreWeights } from "@/lib/growth/data";

const dimensions: Array<[keyof GrowthScore, string, string]> = [["impact","Impact","Higher is better"],["effort","Effort","Lower is better"],["confidence","Confidence","Higher is better"],["cost","Cost","Lower is better"],["risk","Risk","Lower is better"],["alignment","Strategic alignment","Higher is better"]];

export function AdminGrowthScoringEditor({ opportunities, initialWeights, persistence, canEdit }: { opportunities: GrowthOpportunity[]; initialWeights: GrowthScoreWeights; persistence: "demo"|"supabase"; canEdit: boolean }) {
  const [weights,setWeights]=useState(initialWeights); const [scores,setScores]=useState<Record<string,GrowthScore>>(Object.fromEntries(opportunities.map((item)=>[item.slug,item.score]))); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  useEffect(()=>{if(persistence!=="demo")return;const timer=window.setTimeout(()=>{try{const saved=JSON.parse(window.localStorage.getItem("commandly-demo-growth-scoring")||"null") as {weights?:GrowthScoreWeights;scores?:Record<string,GrowthScore>}|null;if(saved?.weights&&saved?.scores){setWeights(saved.weights);setScores(saved.scores)}}catch{/* Keep safe defaults when local prototype data is invalid. */}},0);return()=>window.clearTimeout(timer)},[persistence]);
  const total=useMemo(()=>Object.values(weights).reduce((sum,value)=>sum+value,0),[weights]);
  function setWeight(key:keyof GrowthScore,value:number){setWeights({...weights,[key]:value});setMessage("");}
  function setRating(slug:string,key:keyof GrowthScore,value:number){setScores({...scores,[slug]:{...scores[slug],[key]:value}});setMessage("");}
  async function submit(){if(total!==100){setMessage("Weights must total exactly 100.");return}setSaving(true);if(persistence==="demo"){window.localStorage.setItem("commandly-demo-growth-scoring",JSON.stringify({weights,scores}));setMessage("Demo scoring saved in this browser.");setSaving(false);return}const result=await saveGrowthScoring(weights,scores);setMessage(result.error||"Scoring configuration saved for this organization.");setSaving(false)}
  if(!canEdit)return <div className="card error-card"><h2>Administrator access required</h2><p>Only tenant administrators can change scoring weights and ratings.</p></div>;
  return <div className="coach-admin-stack"><section className="card"><div className="metric-row"><div><span className="badge blue">Organization weights</span><h2 className="growth-method-heading">Configure the 100-point formula</h2></div><span className={`growth-weight-total ${total===100?"valid":"invalid"}`}>{total}/100</span></div><div className="admin-score-grid">{dimensions.map(([key,label,hint])=><label key={key}><span className="label">{label}</span><input className="input" type="number" min="0" max="100" value={weights[key]} onChange={(event)=>setWeight(key,Number(event.target.value))}/><small>{hint}</small></label>)}</div></section><section className="card"><div className="metric-row"><div><span className="badge amber">Opportunity ratings</span><h2 className="growth-method-heading">Rate each opportunity from 1 to 5</h2></div><Calculator size={24}/></div><div className="table-wrap"><table className="table growth-admin-score-table"><thead><tr><th>Opportunity</th>{dimensions.map(([key,label])=><th key={key}>{label}</th>)}<th>Preview</th></tr></thead><tbody>{opportunities.map((item)=><tr key={item.slug}><td><strong>{item.title}</strong><small>{item.category}</small></td>{dimensions.map(([key])=><td key={key}><input aria-label={`${item.title} ${key}`} type="number" min="1" max="5" value={scores[item.slug][key]} onChange={(event)=>setRating(item.slug,key,Number(event.target.value))}/></td>)}<td><strong className="admin-score-preview">{calculateGrowthPriority(scores[item.slug],weights)}</strong></td></tr>)}</tbody></table></div></section><div className="admin-score-actions"><p className={message.includes("saved")?"form-success":"form-error"} aria-live="polite">{message}</p><button className="btn btn-primary" type="button" onClick={submit} disabled={saving||total!==100}>{saving?<><LoaderCircle className="spin" size={16}/> Saving</>:<><Save size={16}/> Save scoring</>}</button></div></div>;
}
