"use client";
import { CheckCircle2, Plus, Save } from "lucide-react";
import { useState } from "react";
import { saveExecutiveDecision } from "@/app/executive/decisions/actions";
import type { ExecutiveDecision, ExecutiveDecisionInput, ExecutiveDecisionStatus } from "@/lib/executive/decisions";

const labels: Record<ExecutiveDecisionStatus, string> = { open: "Open", validated: "Validated", revised: "Revised", reversed: "Reversed" };
const blank = (period: string, priority: string): ExecutiveDecisionInput => ({ priorityKey: priority, reportingPeriod: `${period}-01`, title: "", decision: "", rationale: "", ownerName: "", reviewDate: "", expectedOutcome: "", measuredOutcome: "", status: "open" });
type PriorityOption = { id: string; title: string };

function DecisionFields({ value, change, priorities }: { value: ExecutiveDecisionInput; change: (next: ExecutiveDecisionInput) => void; priorities: PriorityOption[] }) {
  return <><div className="grid grid-2"><label><span className="label">Related priority</span><select className="input" value={value.priorityKey} onChange={(e) => change({ ...value, priorityKey: e.target.value })}>{priorities.length ? priorities.map((p) => <option key={p.id} value={p.id}>{p.title}</option>) : <option value="general-leadership">General leadership</option>}</select></label><label><span className="label">Decision owner</span><input className="input" maxLength={160} required value={value.ownerName} onChange={(e) => change({ ...value, ownerName: e.target.value })}/></label><label><span className="label">Review date</span><input className="input" type="date" required value={value.reviewDate} onChange={(e) => change({ ...value, reviewDate: e.target.value })}/></label><label><span className="label">Status</span><select className="input" value={value.status} onChange={(e) => change({ ...value, status: e.target.value as ExecutiveDecisionStatus })}>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div><label><span className="label">Decision title</span><input className="input" maxLength={180} required value={value.title} onChange={(e) => change({ ...value, title: e.target.value })}/></label><label><span className="label">What was decided</span><textarea className="input" rows={3} maxLength={3000} required value={value.decision} onChange={(e) => change({ ...value, decision: e.target.value })}/></label><label><span className="label">Why this decision was made</span><textarea className="input" rows={2} maxLength={3000} value={value.rationale} onChange={(e) => change({ ...value, rationale: e.target.value })}/></label><label><span className="label">Expected outcome</span><textarea className="input" rows={2} maxLength={2000} required value={value.expectedOutcome} onChange={(e) => change({ ...value, expectedOutcome: e.target.value })}/></label><label><span className="label">Measured outcome</span><textarea className="input" rows={2} maxLength={2000} value={value.measuredOutcome} onChange={(e) => change({ ...value, measuredOutcome: e.target.value })}/><small className="field-help">Required when validated, revised, or reversed.</small></label></>;
}

export function ExecutiveDecisionLog({ initialDecisions, period, priorities, persistence }: { initialDecisions: ExecutiveDecision[]; period: string; priorities: PriorityOption[]; persistence: "demo" | "supabase" }) {
  const [items, setItems] = useState(initialDecisions); const [draft, setDraft] = useState(blank(period, priorities[0]?.id ?? "general-leadership")); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  async function save(input: ExecutiveDecisionInput) { setSaving(true); setError(""); setNotice(""); const result = await saveExecutiveDecision(input); setSaving(false); if (result.error) { setError(result.error); return; } const saved: ExecutiveDecision = { ...input, id: result.decisionId ?? input.id ?? crypto.randomUUID(), updatedAt: new Date().toISOString() }; setItems((current) => input.id ? current.map((item) => item.id === input.id ? saved : item) : [saved, ...current]); if (!input.id) setDraft(blank(period, priorities[0]?.id ?? "general-leadership")); setNotice(persistence === "demo" ? "Decision updated for this prototype view only." : "Decision saved for this organization."); }
  return <div className="executive-decision-layout"><form className="card form-stack" onSubmit={(e) => { e.preventDefault(); save(draft); }}><div className="metric-row"><div><span className="badge blue">New decision</span><h2>Record a leadership decision</h2></div><Plus size={20}/></div><DecisionFields value={draft} change={setDraft} priorities={priorities}/>{error && <p className="form-error">{error}</p>}{notice && <p className="improvement-saved"><CheckCircle2 size={15}/>{notice}</p>}<button className="btn btn-primary" disabled={saving}><Save size={16}/>{saving ? "Saving…" : "Save decision"}</button></form><section className="executive-decision-list" aria-label="Leadership decisions">{items.length ? items.map((item) => <DecisionCard key={item.id} item={item} priorities={priorities} save={save} saving={saving}/>) : <div className="card output empty"><Plus size={28}/><h2>No decisions recorded</h2><p>Record the first leadership decision for this period.</p></div>}</section></div>;
}

function DecisionCard({ item, priorities, save, saving }: { item: ExecutiveDecision; priorities: PriorityOption[]; save: (input: ExecutiveDecisionInput) => void; saving: boolean }) { const [value, setValue] = useState<ExecutiveDecisionInput>(item); return <article className="card executive-decision-card"><div className="metric-row"><div><span className={`badge ${item.status === "validated" ? "blue" : item.status === "open" ? "amber" : ""}`}>{labels[item.status]}</span><h2>{item.title}</h2></div><small>Review {item.reviewDate}</small></div><p>{item.decision}</p><details><summary>Edit decision and outcome</summary><form className="form-stack" onSubmit={(e) => { e.preventDefault(); save(value); }}><DecisionFields value={value} change={setValue} priorities={priorities}/><button className="btn btn-primary" disabled={saving}><Save size={16}/>Save changes</button></form></details></article>; }
