"use client";

import { CheckCircle2, ClipboardCheck, Gauge, LoaderCircle, Save, SearchCheck } from "lucide-react";
import { useState } from "react";
import { saveImprovementWorkflow } from "@/app/operations/improvements/actions";
import type { ImprovementStatus, ProcessImprovement } from "@/lib/operations/improvements";

const departments = ["Management", "Sales", "Service", "Administrative", "Delivery"];
const statuses: ImprovementStatus[] = ["Submitted", "Under review", "Approved", "In progress", "Measuring", "Verified", "Closed"];

export function ImprovementWorkflow({ improvement, persistence = "demo" }: { improvement: ProcessImprovement; persistence?: "demo" | "supabase" }) {
  const [decision,setDecision]=useState(improvement.managerDecision); const [status,setStatus]=useState(improvement.status); const [department,setDepartment]=useState(improvement.department);
  const [managerNote,setManagerNote]=useState(improvement.managerNote); const [owner,setOwner]=useState(improvement.owner); const [dueDate,setDueDate]=useState(improvement.dueDate);
  const [whys,setWhys]=useState(improvement.whys.length?improvement.whys:["","","","",""]); const [action,setAction]=useState(improvement.correctiveAction);
  const [results,setResults]=useState(improvement.results); const [lessons,setLessons]=useState(improvement.lessonsLearned);
  const [phase,setPhase]=useState<"Before"|"After"|"Follow-up">("After"); const [metric,setMetric]=useState(""); const [value,setValue]=useState(""); const [unit,setUnit]=useState("");
  const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(""); const [error,setError]=useState("");
  async function save() { setSaving(true);setError(""); const input={id:improvement.id,decision,status,department,managerNote,owner,dueDate,whys,correctiveAction:action,results,lessonsLearned:lessons,measurement:metric.trim()&&unit.trim()&&value!==""?{phase,metric,value:Number(value),unit}:undefined}; if(persistence==="supabase"){const response=await saveImprovementWorkflow(input);if(response.error){setError(response.error);setSaving(false);return}} setSaving(false);setNotice(persistence==="supabase"?"Saved to the shared workspace.":"Saved for this prototype session.");window.setTimeout(()=>setNotice(""),2200); }
  return <div className="improvement-workflow">
    <section className="card improvement-review-card"><div className="metric-row"><div><span className="badge blue">Manager review</span><h2>Review and decide</h2></div><ClipboardCheck size={19}/></div><div className="grid grid-2"><label><span className="label">Decision</span><select className="input" value={decision} onChange={e=>setDecision(e.target.value as ProcessImprovement["managerDecision"])}><option>Pending</option><option>Approved</option><option>More information</option><option>Not approved</option></select></label><label><span className="label">Status</span><select className="input" value={status} onChange={e=>setStatus(e.target.value as ImprovementStatus)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label></div><label><span className="label">Manager review note</span><textarea className="input" rows={3} value={managerNote} onChange={e=>setManagerNote(e.target.value)}/></label><div className="grid grid-3"><label><span className="label">Department</span><select className="input" value={department} onChange={e=>setDepartment(e.target.value)}>{departments.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="label">Owner</span><input className="input" value={owner} onChange={e=>setOwner(e.target.value)}/></label><label><span className="label">Due date</span><input className="input" type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label></div></section>
    <section className="card"><div className="metric-row"><div><span className="badge blue">Root-cause analysis</span><h2>Five Whys</h2></div><SearchCheck size={19}/></div><div className="improvement-whys">{whys.map((why,index)=><label key={index}><span>{index+1}</span><div><span className="label">Why {index+1}</span><textarea className="input" rows={2} value={why} onChange={e=>setWhys(whys.map((x,i)=>i===index?e.target.value:x))}/></div></label>)}</div></section>
    <section className="card"><span className="badge blue">Improve</span><h2>Corrective action</h2><label><span className="label">Proposed corrective action</span><textarea className="input" rows={5} value={action} onChange={e=>setAction(e.target.value)}/></label></section>
    <section className="card"><div className="metric-row"><div><span className="badge blue">Measure</span><h2>Before-and-after measurements</h2></div><Gauge size={19}/></div><div className="improvement-measurements">{improvement.measurements.map(x=><div key={x.id}><span className={`badge ${x.phase==="Before"?"amber":""}`}>{x.phase}</span><strong>{x.metric}</strong><b>{x.value} {x.unit}</b><small>{x.measuredAt} · {x.verified?"Verified":"Needs verification"}</small></div>)}</div><div className="grid grid-4 improvement-measure-form"><label><span className="label">Phase</span><select className="input" value={phase} onChange={e=>setPhase(e.target.value as typeof phase)}><option>Before</option><option>After</option><option>Follow-up</option></select></label><label><span className="label">Measure</span><input className="input" value={metric} onChange={e=>setMetric(e.target.value)}/></label><label><span className="label">Value</span><input className="input" type="number" min="0" step="0.01" value={value} onChange={e=>setValue(e.target.value)}/></label><label><span className="label">Unit</span><input className="input" value={unit} onChange={e=>setUnit(e.target.value)}/></label></div></section>
    <section className="card"><span className="badge blue">Close the loop</span><h2>Results and lessons learned</h2><label><span className="label">Results</span><textarea className="input" rows={3} value={results} onChange={e=>setResults(e.target.value)}/></label><label><span className="label">Lessons learned</span><textarea className="input" rows={3} value={lessons} onChange={e=>setLessons(e.target.value)}/></label><div className="callout"><CheckCircle2 size={18}/><div><strong>Verification required</strong><p>Only a manager can mark the result verified or closed.</p></div></div></section>
    <section className="card improvement-review-card">{error&&<p className="form-error">{error}</p>}{notice&&<p className="operations-schedule-notice"><CheckCircle2 size={15}/>{notice}</p>}<button className="btn btn-primary" disabled={saving} onClick={save}>{saving?<><LoaderCircle className="spin" size={16}/> Saving workflow</>:<><Save size={16}/> Save improvement workflow</>}</button><small>Saving includes review, assignment, Five Whys, corrective action, measurements, and closeout notes.</small></section>
  </div>;
}
