"use client";

import { AlertCircle, AlertTriangle, CalendarDays, CheckCircle2, Clock3, LoaderCircle, MapPin, Plus, RotateCcw, ShieldAlert, UserRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { saveOperationsAlert, setOperationsAlertStatus } from "@/app/operations/actions";
import type { OperationsAlertRecord } from "@/lib/operations/data";
import type { OperationsPersistence } from "@/lib/operations/repository";
import { formatOperationsDate, readOperationsAlerts, writeOperationsAlerts } from "@/lib/operations/storage";

const statuses: Array<"All statuses" | OperationsAlertRecord["status"]> = ["All statuses", "Open", "Acknowledged", "Resolved"];

export function OperationsAlertManager({ initialAlerts = [], persistence = "demo", initialError = "" }: { initialAlerts?: OperationsAlertRecord[]; persistence?: OperationsPersistence; initialError?: string }) {
  const [alerts, setAlerts] = useState<OperationsAlertRecord[] | null>(persistence === "supabase" ? initialAlerts : null);
  const [error, setError] = useState(initialError);
  const [statusFilter, setStatusFilter] = useState<(typeof statuses)[number]>("All statuses");
  const [title, setTitle] = useState("");
  const [detail, setDetail] = useState("");
  const [severity, setSeverity] = useState<OperationsAlertRecord["severity"]>("Medium");
  const [location, setLocation] = useState("Charleston");
  const [owner, setOwner] = useState("");
  const [dueDate, setDueDate] = useState("");

  useEffect(() => { if (persistence === "supabase") return; const timer = window.setTimeout(() => { try { setAlerts(readOperationsAlerts()); } catch { setError("Saved alerts could not be loaded from this browser."); setAlerts([]); } }, 0); return () => window.clearTimeout(timer); }, [persistence]);
  const filtered = useMemo(() => (alerts ?? []).filter((alert) => statusFilter === "All statuses" || alert.status === statusFilter), [alerts, statusFilter]);
  function save(next: OperationsAlertRecord[]) { try { writeOperationsAlerts(next); setAlerts(next); setError(""); } catch { setError("Alert changes could not be saved in this browser."); } }
  async function createAlert(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (title.trim().length < 2 || detail.trim().length < 10 || owner.trim().length < 2 || !dueDate) { setError("Add a title, useful description, owner, and due date."); return; }
    const input = { title: title.trim(), detail: detail.trim(), severity, location, owner: owner.trim(), dueDate };
    if (persistence === "supabase") { const result = await saveOperationsAlert(input); if (result.error || !result.record) { setError(result.error ?? "Alert could not be created."); return; } setAlerts([result.record, ...(alerts ?? [])]); setError(""); }
    else { const now = new Date().toISOString(); const next: OperationsAlertRecord = { ...input, id: crypto.randomUUID(), status: "Open", createdAt: now, history: [{ id: crypto.randomUUID(), status: "Open", note: "Alert created.", changedAt: now }] }; save([next, ...(alerts ?? [])]); }
    setTitle(""); setDetail(""); setSeverity("Medium"); setOwner(""); setDueDate("");
  }
  async function changeStatus(alertId: string, status: OperationsAlertRecord["status"]) {
    if (!alerts) return; const now = new Date().toISOString(); const note = status === "Acknowledged" ? "Owner acknowledged the alert." : status === "Resolved" ? "Alert marked resolved." : "Alert reopened for follow-up.";
    if (persistence === "demo") save(alerts.map((alert) => alert.id === alertId ? { ...alert, status, history: [...alert.history, { id: crypto.randomUUID(), status, note, changedAt: now }] } : alert));
    else { const result = await setOperationsAlertStatus(alertId, status, note); if (result.error || !result.history) { setError(result.error ?? "Alert could not be updated."); return; } setAlerts(alerts.map((alert) => alert.id === alertId ? { ...alert, status, history: [...alert.history, result.history] } : alert)); setError(""); }
  }
  if (alerts === null && !error) return <div className="card operations-loading"><LoaderCircle className="spin" size={22}/><div><h2>Loading operational alerts</h2><p>Checking this browser for saved exceptions.</p></div></div>;
  const openCount = alerts?.filter((alert) => alert.status === "Open").length ?? 0; const acknowledgedCount = alerts?.filter((alert) => alert.status === "Acknowledged").length ?? 0; const resolvedCount = alerts?.filter((alert) => alert.status === "Resolved").length ?? 0;
  return <>
    <section className="grid grid-3 operations-alert-metrics"><div className="card"><div className="metric-row"><span>Open alerts</span><span className="metric-icon"><AlertCircle size={18}/></span></div><div className="metric">{openCount}</div><span className="delta">Requires ownership</span></div><div className="card"><div className="metric-row"><span>Acknowledged</span><span className="metric-icon"><Clock3 size={18}/></span></div><div className="metric">{acknowledgedCount}</div><span className="delta">Follow-up underway</span></div><div className="card"><div className="metric-row"><span>Resolved</span><span className="metric-icon"><CheckCircle2 size={18}/></span></div><div className="metric">{resolvedCount}</div><span className="delta">Retained in history</span></div></section>
    <div className="operations-alert-workspace"><aside className="card operations-alert-form"><div className="metric-row"><div><span className="badge blue">Local prototype</span><h2>Create an alert</h2></div><span className="metric-icon"><ShieldAlert size={18}/></span></div><p>Capture an operational exception and assign clear responsibility.</p>{error && <p className="form-error operations-procedure-error"><AlertTriangle size={14}/>{error}</p>}<form className="form-stack" onSubmit={createAlert}><label><span className="label">Alert title</span><input className="input" required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Describe the exception"/></label><label><span className="label">What happened?</span><textarea className="input" required rows={4} value={detail} onChange={(event) => setDetail(event.target.value)} placeholder="Explain what needs attention and why."/></label><div className="grid grid-2"><label><span className="label">Severity</span><select className="input" value={severity} onChange={(event) => setSeverity(event.target.value as OperationsAlertRecord["severity"])}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label><label><span className="label">Location</span><select className="input" value={location} onChange={(event) => setLocation(event.target.value)}><option>Charleston</option><option>Summerville</option><option>All locations</option></select></label></div><label><span className="label">Owner</span><input className="input" required value={owner} onChange={(event) => setOwner(event.target.value)} placeholder="Person or team"/></label><label><span className="label">Due date</span><input className="input" required type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)}/></label><button className="btn btn-primary" type="submit"><Plus size={16}/> Create alert</button></form></aside>
      <section><div className="operations-alert-toolbar"><div><h2>Alert queue</h2><p>{filtered.length} of {alerts?.length ?? 0} alerts</p></div><label><span className="label">Status</span><select className="input" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as (typeof statuses)[number])}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label></div>{filtered.length ? <div className="operations-managed-alerts">{filtered.map((alert) => <article className={`card operations-managed-alert severity-${alert.severity.toLowerCase()}`} key={alert.id}><div className="metric-row"><div className="operations-alert-badges"><span className={`badge ${alert.status === "Resolved" ? "" : alert.status === "Acknowledged" ? "blue" : "amber"}`}>{alert.status}</span><span className={`severity-label severity-${alert.severity.toLowerCase()}`}>{alert.severity}</span></div><small>Created {new Date(alert.createdAt).toLocaleDateString()}</small></div><h2>{alert.title}</h2><p>{alert.detail}</p><div className="operations-assigned-meta"><span><MapPin size={14}/>{alert.location}</span><span><UserRound size={14}/>{alert.owner}</span><span><CalendarDays size={14}/>Due {formatOperationsDate(alert.dueDate)}</span></div><div className="operations-alert-actions">{alert.status === "Open" && <button className="btn btn-secondary" type="button" onClick={() => changeStatus(alert.id, "Acknowledged")}><Clock3 size={15}/> Acknowledge</button>}{alert.status !== "Resolved" && <button className="btn btn-primary" type="button" onClick={() => changeStatus(alert.id, "Resolved")}><CheckCircle2 size={15}/> Resolve</button>}{alert.status === "Resolved" && <button className="btn btn-ghost" type="button" onClick={() => changeStatus(alert.id, "Open")}><RotateCcw size={15}/> Reopen</button>}</div><details className="operations-alert-history"><summary>View status history</summary><ol>{[...alert.history].reverse().map((entry) => <li key={entry.id}><strong>{entry.status}</strong><span>{entry.note}</span><small>{new Date(entry.changedAt).toLocaleString()}</small></li>)}</ol></details></article>)}</div> : <div className="card output empty"><div><CheckCircle2 size={28}/><h2>No alerts in this view</h2><p>Change the status filter or create a new alert.</p></div></div>}</section>
    </div>
  </>;
}
