"use client";

import { AlertTriangle, ArrowRight, ArrowRightLeft, CheckCircle2, Clock3, LoaderCircle, MapPin, Plus, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { saveOperationsHandoff, setOperationsHandoffStatus } from "@/app/operations/actions";
import type { OperationsHandoffRecord } from "@/lib/operations/data";
import type { OperationsPersistence } from "@/lib/operations/repository";
import { readOperationsHandoffs, writeOperationsHandoffs } from "@/lib/operations/storage";

const statuses = ["All statuses", "Open", "Acknowledged", "Closed"] as const;

export function OperationsHandoffManager({ initialHandoffs = [], persistence = "demo", initialError = "" }: { initialHandoffs?: OperationsHandoffRecord[]; persistence?: OperationsPersistence; initialError?: string }) {
  const [handoffs, setHandoffs] = useState<OperationsHandoffRecord[] | null>(persistence === "supabase" ? initialHandoffs : null);
  const [location, setLocation] = useState("Charleston"); const [fromShift, setFromShift] = useState("Opening"); const [toShift, setToShift] = useState("Closing");
  const [summary, setSummary] = useState(""); const [issues, setIssues] = useState(""); const [decisions, setDecisions] = useState(""); const [owner, setOwner] = useState("");
  const [statusFilter, setStatusFilter] = useState<(typeof statuses)[number]>("All statuses"); const [locationFilter, setLocationFilter] = useState("All locations"); const [error, setError] = useState(initialError);

  useEffect(() => { if (persistence === "supabase") return; const timer = window.setTimeout(() => { try { setHandoffs(readOperationsHandoffs()); } catch { setError("Handoff logs could not be loaded from this browser."); setHandoffs([]); } }, 0); return () => window.clearTimeout(timer); }, [persistence]);
  function save(next: OperationsHandoffRecord[]) { try { writeOperationsHandoffs(next); setHandoffs(next); setError(""); } catch { setError("Handoff changes could not be saved in this browser."); } }
  async function createHandoff(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (summary.trim().length < 3 || owner.trim().length < 2) { setError("Add a clear summary and next-action owner."); return; } const input = { location, fromShift, toShift, summary: summary.trim(), unresolvedIssues: issues.trim() || "None reported.", decisions: decisions.trim() || "No new decisions recorded.", owner: owner.trim() }; if (persistence === "supabase") { const result = await saveOperationsHandoff(input); if (result.error || !result.record) { setError(result.error ?? "Handoff could not be created."); return; } setHandoffs([result.record, ...(handoffs ?? [])]); setError(""); } else { const now = new Date().toISOString(); save([{ ...input, id: crypto.randomUUID(), status: "Open", createdAt: now, updatedAt: now }, ...(handoffs ?? [])]); } setSummary(""); setIssues(""); setDecisions(""); setOwner(""); }
  async function changeStatus(id: string, status: OperationsHandoffRecord["status"]) { if (!handoffs) return; if (persistence === "demo") save(handoffs.map((item) => item.id === id ? { ...item, status, updatedAt: new Date().toISOString() } : item)); else { const result = await setOperationsHandoffStatus(id, status); if (result.error) { setError(result.error); return; } setHandoffs(handoffs.map((item) => item.id === id ? { ...item, status, updatedAt: result.updatedAt ?? item.updatedAt } : item)); setError(""); } }
  if (handoffs === null && !error) return <div className="card operations-loading"><LoaderCircle className="spin" size={22}/><div><h2>Loading handoff logs</h2><p>Checking this browser for saved shift context.</p></div></div>;
  const locations = [...new Set((handoffs ?? []).map((item) => item.location))]; const filtered = (handoffs ?? []).filter((item) => (statusFilter === "All statuses" || item.status === statusFilter) && (locationFilter === "All locations" || item.location === locationFilter));
  const open = handoffs?.filter((item) => item.status === "Open").length ?? 0; const acknowledged = handoffs?.filter((item) => item.status === "Acknowledged").length ?? 0; const closed = handoffs?.filter((item) => item.status === "Closed").length ?? 0;

  return <div className="operations-handoff-stack"><section className="grid grid-3"><div className="card"><div className="metric-row"><span>Open handoffs</span><span className="metric-icon"><ArrowRightLeft size={18}/></span></div><div className="metric">{open}</div><span className="delta">Awaiting acknowledgment</span></div><div className="card"><div className="metric-row"><span>Acknowledged</span><span className="metric-icon"><Clock3 size={18}/></span></div><div className="metric">{acknowledged}</div><span className="delta">Follow-up underway</span></div><div className="card"><div className="metric-row"><span>Closed</span><span className="metric-icon"><CheckCircle2 size={18}/></span></div><div className="metric">{closed}</div><span className="delta">Retained in history</span></div></section>{error && <p className="form-error operations-schedule-message"><AlertTriangle size={15}/>{error}</p>}
    <div className="operations-handoff-layout"><aside className="card operations-handoff-form"><div className="metric-row"><div><span className="badge blue">Local prototype</span><h2>Create a handoff</h2></div><span className="metric-icon"><Plus size={18}/></span></div><p>Capture only the context the next shift needs to act confidently.</p><form className="form-stack" onSubmit={createHandoff}><div className="grid grid-2"><label><span className="label">Location</span><select className="input" value={location} onChange={(e) => setLocation(e.target.value)}><option>Charleston</option><option>Summerville</option><option>All locations</option></select></label><label><span className="label">Next-action owner</span><input className="input" required value={owner} onChange={(e) => setOwner(e.target.value)} placeholder="Person or team"/></label></div><div className="grid grid-2"><label><span className="label">From shift</span><select className="input" value={fromShift} onChange={(e) => setFromShift(e.target.value)}><option>Opening</option><option>Midday</option><option>Closing</option></select></label><label><span className="label">To shift</span><select className="input" value={toShift} onChange={(e) => setToShift(e.target.value)}><option>Opening</option><option>Midday</option><option>Closing</option></select></label></div><label><span className="label">Shift summary</span><textarea className="input" required rows={3} value={summary} onChange={(e) => setSummary(e.target.value)} placeholder="What happened during this shift?"/></label><label><span className="label">Unresolved issues</span><textarea className="input" rows={3} value={issues} onChange={(e) => setIssues(e.target.value)} placeholder="What still needs attention?"/></label><label><span className="label">Decisions and next steps</span><textarea className="input" rows={3} value={decisions} onChange={(e) => setDecisions(e.target.value)} placeholder="What was decided and what happens next?"/></label><button className="btn btn-primary" type="submit"><Plus size={16}/> Create handoff</button></form></aside>
      <section><div className="operations-handoff-toolbar"><div><h2>Handoff history</h2><p>{filtered.length} of {handoffs?.length ?? 0} records</p></div><label><span className="label">Location</span><select className="input" value={locationFilter} onChange={(e) => setLocationFilter(e.target.value)}><option>All locations</option>{locations.map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="label">Status</span><select className="input" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as (typeof statuses)[number])}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label></div>{filtered.length ? <div className="operations-handoff-list">{filtered.map((item) => <article className="card operations-handoff-card" key={item.id}><div className="metric-row"><span className={`badge ${item.status === "Open" ? "amber" : item.status === "Acknowledged" ? "blue" : ""}`}>{item.status}</span><small>{new Date(item.createdAt).toLocaleString()}</small></div><div className="operations-handoff-route"><strong>{item.fromShift}</strong><ArrowRight size={16}/><strong>{item.toShift}</strong></div><h2>{item.summary}</h2><div className="operations-assigned-meta"><span><MapPin size={14}/>{item.location}</span><span><UserRound size={14}/>{item.owner}</span></div><div className="operations-handoff-details"><div><small>Unresolved issues</small><p>{item.unresolvedIssues}</p></div><div><small>Decisions and next steps</small><p>{item.decisions}</p></div></div><div className="operations-handoff-actions">{item.status === "Open" && <button className="btn btn-secondary" onClick={() => changeStatus(item.id, "Acknowledged")}><Clock3 size={15}/> Acknowledge</button>}{item.status !== "Closed" && <button className="btn btn-primary" onClick={() => changeStatus(item.id, "Closed")}><CheckCircle2 size={15}/> Close handoff</button>}</div></article>)}</div> : <div className="card output empty"><div><ArrowRightLeft size={28}/><h2>No handoffs in this view</h2><p>Change the filters or create a new handoff.</p></div></div>}</section></div>
  </div>;
}
