"use client";

import { Check, GitCompareArrows, ImageIcon } from "lucide-react";
import { useMemo, useState } from "react";
import type { ProductDTO } from "@/lib/products/types";

const coreFields: Array<[string, (p: ProductDTO) => string]> = [
  ["Brand", p => p.brand || "Not provided"], ["Model year", p => p.modelYear ? String(p.modelYear) : "Not provided"], ["Model", p => [p.name, p.model, p.modelVariant].filter(Boolean).join(" · ") || "Not provided"], ["Category", p => p.productCategory || "Not provided"], ["MSRP", p => p.price ? `$${p.price.toLocaleString()}` : "Not provided"], ["Sale price", p => p.salePrice == null ? "Not provided" : `$${p.salePrice.toLocaleString()}`], ["Passenger capacity", p => p.seats || "Not provided"], ["Powertrain", p => p.powertrain || "Not provided"], ["Range", p => p.range || "Not provided"], ["Dimensions", p => p.dimensions || "Not provided"], ["Turning radius", p => p.turningRadius || "Not provided"], ["Maximum load", p => p.maxLoadCapacity || "Not provided"],
];
const specificationLabels: Record<string, string> = { batteryType: "Battery", batteryVoltage: "Battery voltage", batteryCapacity: "Battery capacity", motor: "Motor", controller: "Controller", horsepower: "Horsepower", topSpeed: "Top speed", chargingTime: "Charging time", brakes: "Brakes", suspension: "Suspension", steering: "Steering", frameMaterial: "Frame material", display: "Display", audioSystem: "Audio system", lighting: "Lighting", safetyFeatures: "Safety features", warranty: "Warranty", standardFeatures: "Standard features" };
const display = (value: string) => value.trim() || "Not provided";

export function ProductComparison({ products }: { products: ProductDTO[] }) {
  const ours = useMemo(() => products.filter(p => (p.productType || "our_product") === "our_product"), [products]);
  const competitors = useMemo(() => products.filter(p => p.productType === "competitor_product"), [products]);
  const [ourId, setOurId] = useState(ours[0]?.id || "");
  const [competitorId, setCompetitorId] = useState(competitors[0]?.id || "");
  const selected = [ours.find(p => p.id === ourId), competitors.find(p => p.id === competitorId)].filter((p): p is ProductDTO => Boolean(p));
  const fields = useMemo(() => [...coreFields, ...Object.entries(specificationLabels).map(([key, label]) => [label, (p: ProductDTO) => p.specifications?.[key] || "Not provided"] as [string, (p: ProductDTO) => string])], []);
  if (!ours.length || !competitors.length) return <div className="card output empty"><div><h2>Products needed for a comparison</h2><p>Publish at least one Our Product and one Competitor Product. Competitors remain separate from your sales catalog.</p></div></div>;
  return <div className="comparison-workspace"><section className="card comparison-picker"><div className="comparison-picker-heading"><div><h2>Choose products</h2><p>Our Products and Competitor Products are kept separate. Model year is shown for every selection.</p></div><span className="badge blue"><GitCompareArrows size={14}/> Grounded comparison</span></div><div className="comparison-selectors"><label className="comparison-selector"><span className="label">Our Product</span><select className="input" value={ourId} onChange={e => setOurId(e.target.value)}>{ours.map(p => <option key={p.id} value={p.id}>{p.modelYear || "Year not provided"} {p.brand || ""} {p.name} {p.modelVariant || ""}</option>)}</select></label><label className="comparison-selector"><span className="label">Competitor Product</span><select className="input" value={competitorId} onChange={e => setCompetitorId(e.target.value)}>{competitors.map(p => <option key={p.id} value={p.id}>{p.modelYear || "Year not provided"} {p.brand || ""} {p.name} {p.modelVariant || ""}</option>)}</select></label></div></section><div className="comparison-table-wrap"><div className="comparison-detail-grid" style={{gridTemplateColumns:"minmax(160px,.55fr) repeat(2,minmax(230px,1fr))"}}><div className="comparison-corner">Product details</div>{selected.map((product, index) => <article className="comparison-product-head" key={product.id}>{product.imageUrl ? <div className="comparison-product-image" style={{backgroundImage:`url(${product.imageUrl})`}}/> : <div className={`comparison-product-image placeholder ${product.color}`}><ImageIcon size={28}/></div>}<span className={`badge ${index ? "amber" : "blue"}`}>{index ? "COMPETITOR PRODUCT" : "OUR PRODUCT"}</span><h2>{product.name}</h2><p>{product.modelYear || "Model year not provided"} · {product.brand || "Brand not provided"}</p></article>)}{fields.map(([label, value]) => <div className="comparison-row" key={label} style={{gridColumn:"1 / -1",gridTemplateColumns:"minmax(160px,.55fr) repeat(2,minmax(230px,1fr))"}}><div className="comparison-label">{label}</div>{selected.map(p => <div className="comparison-value" key={`${label}-${p.id}`}>{display(value(p))}</div>)}</div>)}<div className="comparison-row" style={{gridColumn:"1 / -1",gridTemplateColumns:"minmax(160px,.55fr) repeat(2,minmax(230px,1fr))"}}><div className="comparison-label">Standard features</div>{selected.map(p => <div className="comparison-value comparison-highlights" key={p.id}>{p.highlights.length ? <ul>{p.highlights.map(item => <li key={item}><Check size={15}/>{item}</li>)}</ul> : "Not provided"}</div>)}</div></div></div></div>;
}
