import { AlertTriangle, CheckCircle2, Clock3, FileEdit } from "lucide-react";
import type { SalesDataQualityWorkspace } from "@/lib/sales/results";

const statusCopy = { approved: "Approved", draft: "Draft", missing: "Missing", outdated: "Outdated" } as const;
const statusIcon = { approved: CheckCircle2, draft: FileEdit, missing: AlertTriangle, outdated: Clock3 } as const;

export function SalesDataQualityReview({ workspace }: { workspace: SalesDataQualityWorkspace }) {
  return <><section className="grid grid-4 sales-quality-counts" aria-label="Sales data-quality summary">{(["approved","draft","missing","outdated"] as const).map((status) => { const Icon = statusIcon[status]; return <article className="card" key={status}><div className="metric-row"><span>{statusCopy[status]}</span><span className={`metric-icon quality-${status}`}><Icon size={18}/></span></div><strong className="metric">{workspace.counts[status]}</strong><small>{status === "approved" ? "ready for leadership reporting" : status === "draft" ? "awaiting administrator approval" : status === "outdated" ? "using an older reporting month" : "no result recorded"}</small></article>; })}</section><section className="card sales-quality-card"><div className="section-heading"><div><span className="badge blue">Location readiness</span><h2>Monthly reporting review</h2><p>Every active location should have one approved result for the selected month.</p></div></div><div className="executive-table-scroll"><table><thead><tr><th>Location</th><th>Status</th><th>Selected month</th><th>Latest record</th><th>Revenue readiness</th></tr></thead><tbody>{workspace.quality.map((item) => <tr key={item.locationId}><td><strong>{item.locationName}</strong></td><td><span className={`badge quality-badge ${item.status}`}>{statusCopy[item.status]}</span></td><td>{new Date(`${item.periodStart}T12:00:00`).toLocaleDateString(undefined,{month:"short",year:"numeric"})}</td><td>{item.latestPeriod ? new Date(`${item.latestPeriod}T12:00:00`).toLocaleDateString(undefined,{month:"short",year:"numeric"}) : "—"}</td><td>{item.result ? item.result.revenueTarget > 0 ? `${Math.round(item.result.revenueActual / item.result.revenueTarget * 100)}% of target` : "Target missing" : "Not ready"}</td></tr>)}</tbody></table></div></section></>;
}
