"use client";

import { useActionState, useState } from "react";
import Link from "next/link";
import { Eye, Plus, Save, Send, Trash2 } from "lucide-react";
import { saveGeneratedLesson, type LessonActionState } from "@/app/training/[id]/review/actions";
import { DeleteTrainingDraftButton } from "@/components/delete-training-draft-button";
import type { GeneratedTrainingContent, TrainingQuestion, TrainingQuestionType } from "@/lib/training/generated";
import type { TrainingLessonDTO } from "@/lib/training/types";

const initialState: LessonActionState = { error: "", success: "" };
const newQuestion = (): TrainingQuestion => ({ id: crypto.randomUUID(), type: "multiple_choice", question: "", options: ["", ""], correctAnswer: "", explanation: "", sourceEvidence: "" });

export function TrainingLessonEditor({ lesson }: { lesson: TrainingLessonDTO }) {
  const [state, action, pending] = useActionState(saveGeneratedLesson, initialState);
  const [content, setContent] = useState<GeneratedTrainingContent>(lesson.content);
  const updateList = (key: "learningObjectives" | "keyTakeaways", index: number, value: string) => setContent((current) => ({ ...current, [key]: current[key].map((item, itemIndex) => itemIndex === index ? value : item) }));
  const updateQuestion = (index: number, change: Partial<TrainingQuestion>) => setContent((current) => ({ ...current, knowledgeCheck: current.knowledgeCheck.map((question, questionIndex) => questionIndex === index ? { ...question, ...change } : question) }));

  return <form action={action} className="training-editor">
    <input type="hidden" name="lessonId" value={lesson.id}/>
    <input type="hidden" name="includeKnowledgeCheck" value={String(lesson.includeKnowledgeCheck)}/>
    <input type="hidden" name="content" value={JSON.stringify(content)}/>
    <div className="card training-editor-heading"><div><span className="badge amber">AI Generated — {state.published || lesson.isPublished ? "Published" : "Draft"}</span><h2>Review before publishing</h2><p>Verify every statement against <strong>{lesson.sourceFilename}</strong>. Publishing never changes the source document.</p></div><div className="training-editor-actions"><Link className="btn btn-secondary" href={`/training/${lesson.id}/preview`}><Eye size={15}/> Preview employee view</Link><button className="btn btn-secondary" name="intent" value="draft" disabled={pending}><Save size={15}/> Save Draft</button><button className="btn btn-primary" name="intent" value="publish" disabled={pending}><Send size={15}/> Publish</button>{!lesson.isPublished ? <DeleteTrainingDraftButton lessonId={lesson.id} title={lesson.title} redirectTo="/training/review"/> : null}</div></div>
    {lesson.sourceReviewRequired && <div className="card training-review-alert"><strong>Source Updated — Training Review Recommended</strong><p>The linked document changed after this lesson was generated. The approved lesson was preserved.</p></div>}
    {state.error && <p className="form-error" role="alert">{state.error}</p>}{state.success && <p className="form-success" role="status">{state.success}</p>}
    <section className="card training-editor-section"><h2>Lesson details</h2><label><span className="label">Title</span><input className="input" name="title" defaultValue={lesson.title} required maxLength={140}/></label><label><span className="label">Description</span><textarea className="input" name="description" defaultValue={lesson.description} rows={3}/></label><div className="training-source-summary"><span><strong>Source</strong>{lesson.sourceFilename}</span><span><strong>Estimated Time</strong>{lesson.estimatedMinutes} minutes</span><span><strong>Location</strong>{lesson.locationName || "All locations"}</span></div></section>
    <EditableList title="Learning Objectives" values={content.learningObjectives} onChange={(index, value) => updateList("learningObjectives", index, value)} onAdd={() => setContent((current) => ({ ...current, learningObjectives: [...current.learningObjectives, ""] }))} onDelete={(index) => setContent((current) => ({ ...current, learningObjectives: current.learningObjectives.filter((_, itemIndex) => itemIndex !== index) }))}/>
    <section className="card training-editor-section"><div className="metric-row"><h2>Lesson Content</h2><button className="btn btn-secondary" type="button" onClick={() => setContent((current) => ({ ...current, sections: [...current.sections, { title: "", content: "" }] }))}><Plus size={14}/> Add section</button></div>{content.sections.map((section, index) => <div className="training-editor-item" key={index}><button className="icon-button danger-button" type="button" aria-label="Delete section" onClick={() => setContent((current) => ({ ...current, sections: current.sections.filter((_, itemIndex) => itemIndex !== index) }))}><Trash2 size={15}/></button><input className="input" aria-label={`Section ${index + 1} title`} value={section.title} onChange={(event) => setContent((current) => ({ ...current, sections: current.sections.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item) }))}/><textarea className="input" aria-label={`Section ${index + 1} content`} rows={6} value={section.content} onChange={(event) => setContent((current) => ({ ...current, sections: current.sections.map((item, itemIndex) => itemIndex === index ? { ...item, content: event.target.value } : item) }))}/></div>)}</section>
    <EditableList title="Key Takeaways" values={content.keyTakeaways} onChange={(index, value) => updateList("keyTakeaways", index, value)} onAdd={() => setContent((current) => ({ ...current, keyTakeaways: [...current.keyTakeaways, ""] }))} onDelete={(index) => setContent((current) => ({ ...current, keyTakeaways: current.keyTakeaways.filter((_, itemIndex) => itemIndex !== index) }))}/>
    <section className="card training-editor-section"><h2>Practical Application</h2><textarea className="input" rows={6} value={content.practicalApplication} onChange={(event) => setContent((current) => ({ ...current, practicalApplication: event.target.value }))}/><h2>Scenario</h2><label><span className="label">Title</span><input className="input" value={content.scenario?.title || ""} onChange={(event) => setContent((current) => ({ ...current, scenario: { title: event.target.value, situation: current.scenario?.situation || "", recommendedApproach: current.scenario?.recommendedApproach || "" } }))}/></label><label><span className="label">Situation</span><textarea className="input" rows={4} value={content.scenario?.situation || ""} onChange={(event) => setContent((current) => ({ ...current, scenario: { title: current.scenario?.title || "Scenario", situation: event.target.value, recommendedApproach: current.scenario?.recommendedApproach || "" } }))}/></label><label><span className="label">Recommended approach</span><textarea className="input" rows={4} value={content.scenario?.recommendedApproach || ""} onChange={(event) => setContent((current) => ({ ...current, scenario: { title: current.scenario?.title || "Scenario", situation: current.scenario?.situation || "", recommendedApproach: event.target.value } }))}/></label></section>
    {lesson.includeKnowledgeCheck && <section className="card training-editor-section"><div className="metric-row"><div><h2>Knowledge Check</h2><p>Each answer requires an exact excerpt from the source document.</p></div><button className="btn btn-secondary" type="button" onClick={() => setContent((current) => ({ ...current, knowledgeCheck: [...current.knowledgeCheck, newQuestion()] }))}><Plus size={14}/> Add question</button></div>{content.knowledgeCheck.map((question, index) => <div className="training-question-editor" key={question.id}><div className="metric-row"><strong>Question {index + 1}</strong><button className="icon-button danger-button" type="button" aria-label={`Delete question ${index + 1}`} onClick={() => setContent((current) => ({ ...current, knowledgeCheck: current.knowledgeCheck.filter((_, questionIndex) => questionIndex !== index) }))}><Trash2 size={15}/></button></div><label><span className="label">Type</span><select className="input" value={question.type} onChange={(event) => updateQuestion(index, { type: event.target.value as TrainingQuestionType })}><option value="multiple_choice">Multiple choice</option><option value="true_false">True / false</option><option value="scenario">Scenario-based</option></select></label><label><span className="label">Question</span><textarea className="input" rows={2} value={question.question} onChange={(event) => updateQuestion(index, { question: event.target.value })}/></label><label><span className="label">Answer options (one per line)</span><textarea className="input" rows={4} value={question.options.join("\n")} onChange={(event) => updateQuestion(index, { options: event.target.value.split("\n") })}/></label><label><span className="label">Correct answer (must exactly match an option)</span><input className="input" value={question.correctAnswer} onChange={(event) => updateQuestion(index, { correctAnswer: event.target.value })}/></label><label><span className="label">Explanation</span><textarea className="input" rows={3} value={question.explanation} onChange={(event) => updateQuestion(index, { explanation: event.target.value })}/></label><label><span className="label">Exact source evidence</span><textarea className="input" rows={2} value={question.sourceEvidence} onChange={(event) => updateQuestion(index, { sourceEvidence: event.target.value })}/></label></div>)}</section>}
  </form>;
}

function EditableList({ title, values, onChange, onAdd, onDelete }: { title: string; values: string[]; onChange: (index: number, value: string) => void; onAdd: () => void; onDelete: (index: number) => void }) {
  return <section className="card training-editor-section"><div className="metric-row"><h2>{title}</h2><button className="btn btn-secondary" type="button" onClick={onAdd}><Plus size={14}/> Add</button></div>{values.map((value, index) => <div className="training-list-editor" key={index}><input className="input" aria-label={`${title} ${index + 1}`} value={value} onChange={(event) => onChange(index, event.target.value)}/><button className="icon-button danger-button" type="button" aria-label={`Delete ${title.toLowerCase()} ${index + 1}`} onClick={() => onDelete(index)}><Trash2 size={15}/></button></div>)}</section>;
}
