import { Calculator, Scale, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { GrowthPriorityTable } from "@/components/growth-priority-table";
import { PageHeader } from "@/components/page-header";
import { getGrowthScoring } from "@/lib/growth/scoring";

export default async function GrowthPrioritiesPage() {
  const scoring = await getGrowthScoring();
  const weights = scoring.weights;
  return <AppShell title="Growth Priority Scoring"><PageHeader eyebrow="Transparent prioritization" title="Compare opportunities using the same rules" description="Use consistent, explainable ratings to decide which ideas deserve validation first."/><div className="callout growth-disclaimer"><Calculator size={20}/><div><strong>Deterministic scoring</strong><p>Scores use tenant-configured inputs and a published formula. They are planning aids—not predictions, verified financial estimates, or AI recommendations.</p></div></div><div className="grid grid-3 growth-metrics"><div className="card"><div className="metric-row"><span>Positive factors</span><span className="metric-icon"><Scale size={18}/></span></div><h2 className="growth-method-heading">Impact, confidence, alignment</h2><p>Higher ratings increase priority.</p></div><div className="card"><div className="metric-row"><span>Constraint factors</span><span className="metric-icon"><ShieldCheck size={18}/></span></div><h2 className="growth-method-heading">Effort, cost, risk</h2><p>Lower ratings increase priority.</p></div><div className="card"><div className="metric-row"><span>Current weighting</span><span className="metric-icon"><Calculator size={18}/></span></div><h2 className="growth-method-heading">100-point total</h2><p>Impact {weights.impact}% · Confidence {weights.confidence}% · Alignment {weights.alignment}%.</p></div></div><div className="section-heading"><div><h2>Ranked opportunities</h2><p>Select a column to compare opportunities by one scoring dimension.</p></div></div><GrowthPriorityTable opportunities={scoring.opportunities} weights={weights}/><details className="states growth-formula"><summary>How the priority score is calculated</summary><p>Each dimension is rated from 1 to 5. Positive factors use their rating directly. Effort, cost, and risk are reversed so lower constraints improve the result. All tenant-configured weights must total 100.</p><code>Priority = weighted positive factors + weighted inverse constraints</code></details></AppShell>;
}
