import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { getAssistantAnalytics } from "@/lib/assistant/analytics";

function List({ title, items }: { title: string; items: readonly { label: string; count: number }[] }) { return <section className="card"><h2>{title}</h2>{items.length ? items.map((item) => <div className="metric-row" key={item.label}><span>{item.label}</span><strong>{item.count}</strong></div>) : <p>No activity for this period.</p>}</section>; }
export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ view?: string; location?: string; rep?: string; days?: string }> }) {
  const params = await searchParams; const data = await getAssistantAnalytics(params); if (!data.allowed) return <AppShell title="Sales Assistant Analytics"><PageHeader eyebrow="Sales Assistant" title="Analytics unavailable" description={data.reason}/></AppShell>;
  const view = data.scope; const breadcrumb = view === "company" ? "Company" : view === "store" ? "Company > Store" : "Company > Store > Rep";
  const url = (next: Record<string, string>) => `/analytics?${new URLSearchParams({ view, days: data.days, ...next })}`; const tableRows = view === "company" ? data.stores.map((item) => ({ ...item, activity: item.users })) : data.reps.map((item) => ({ ...item, activity: 0 }));
  return <AppShell title="Sales Assistant Analytics"><PageHeader eyebrow={breadcrumb} title="Sales Assistant Analytics" description="Understand the questions your team asks, the knowledge they need, and where coaching can help."/>
    <form className="card" method="get" style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "end" }}><label><span className="label">View</span><select className="input" name="view" defaultValue={view}><option value="company">Company</option><option value="store">Store</option><option value="rep">Rep</option></select></label>{view !== "rep" && <label><span className="label">Store</span><select className="input" name="location" defaultValue={data.selectedLocation}><option value="">All authorized stores</option>{data.locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label>}<label><span className="label">Period</span><select className="input" name="days" defaultValue={data.days}><option value="7">Last 7 Days</option><option value="30">Last 30 Days</option><option value="90">Last 90 Days</option></select></label><button className="btn btn-primary">Apply</button></form>
    <div className="grid grid-4"><section className="card"><span>Questions</span><div className="metric">{data.totals.questions}</div></section><section className="card"><span>Active users</span><div className="metric">{data.totals.activeUsers}</div></section><section className="card"><span>Questions per rep</span><div className="metric">{data.totals.averagePerRep}</div></section><section className="card"><span>Unresolved</span><div className="metric">{data.totals.unresolved}</div></section></div>
    <div className="grid grid-2" style={{ marginTop: 18 }}><List title="Usage trend" items={data.trend}/><List title="Top topics" items={data.topics}/><List title="Product questions" items={data.products}/><List title="Competitor questions" items={data.competitors}/><List title="Top objections" items={data.objections}/><section className="card"><h2>Grounded responses</h2><div className="metric">{data.totals.grounded}</div><p>{data.totals.questions ? `${Math.round(data.totals.grounded / data.totals.questions * 100)}% grounded in approved knowledge` : "No questions in this period."}</p></section></div>
    {view !== "rep" && <section className="card" style={{ marginTop: 18 }}><h2>{view === "company" ? "Store comparison" : "Rep usage"}</h2><div className="table-wrap"><table className="table"><thead><tr><th>{view === "company" ? "Store" : "Rep"}</th><th>Questions</th><th>Active users</th><th></th></tr></thead><tbody>{tableRows.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.questions}</td><td>{view === "company" ? item.activity : "—"}</td><td>{view === "company" ? <Link className="text-button" href={url({ view: "store", location: item.id })}>View store</Link> : <Link className="text-button" href={url({ view: "rep", rep: item.id })}>View rep</Link>}</td></tr>)}</tbody></table></div></section>}
    {view === "rep" && <section className="card" style={{ marginTop: 18 }}><h2>Recent Sales Assistant activity</h2>{data.recent.length ? data.recent.map((item) => <div className="activity-row" key={`${item.question}-${item.created_at}`}><p><strong>{item.question}</strong><small style={{ display: "block" }}>{item.topic} · {new Date(item.created_at).toLocaleDateString()}</small></p><span className={item.unresolved ? "badge amber" : "badge blue"}>{item.unresolved ? "Needs knowledge" : "Grounded"}</span></div>) : <p>No activity for this period.</p>}</section>}
  </AppShell>;
}
